# Generated by Django 5.0.4 on 2024-05-05 16:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('target_amount', models.DecimalField(decimal_places=2, default=None, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Минимально заплонированная сумма сбора в рублях - 0.01.')], verbose_name='Сумма')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Обложка')),
                ('endtime', models.DateTimeField(verbose_name='Дата завершение сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сбора')),
            ],
            options={
                'verbose_name': 'сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ('-created_at',),
                'default_related_name': 'collects',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'событие сбора',
                'verbose_name_plural': 'События сборов',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Минимальная сумма платежа в рублях- 0.01.')], verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления платежа')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'Платяжи',
                'ordering': ('-created_at',),
                'default_related_name': 'payments',
            },
        ),
    ]
